name: app

on:
  push:
    branches: [ "main", release-*, develop ]
  pull_request:
    branches: [ "main", release-*, develop ]
  workflow_dispatch:

jobs:
    Linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'true'
            fetch-depth: 0

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.x

        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v3.0.3
          with:
            versionSpec: '6.0.5'

        - name: Run make linux-x64
          run: make app_linux

        - name: Determine Version
          id:   gitversion
          uses: gittools/actions/gitversion/execute@v3.0.3

        - name: Upload package x64
          uses: actions/upload-artifact@v4
          with:
            name: app-linux-x64-${{ steps.gitversion.outputs.FullSemVer }}
            path: artifacts/linux-x64